version: "3.9"

services:
  synergy_refs:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.envfile
    volumes:
      - ./src:/app
      - ./data:/data
    ports:
      - "8000:8000"
